services:
  - type: web
    name: vigoss
    env: static
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
      - path: /style.css
        name: Cache-Control
        value: public, max-age=86400
      - path: /script.js
        name: Cache-Control
        value: public, max-age=86400
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
